### ISSUE TITLE
remove unused keys in translator

### ISSUE THREAD

**Issue by dfguerrerom** [sepal-contrib/se.plan#145]
I was translating some keys in the crowdin project and I realized there's a variable that is never used: https://github.com/sepal-contrib/se.plan/blob/756141ac6d415244c449bba57b959d2b6f6118d5/component/tile/dashboard_tile.py#L19 and it has a key in the dictionary, so I assume that chances are to find others. To this, I think that using `flake8` will help a lot.

Additionally, by using the translator `use_key` method, there are 109 unused keys, if we assume the format `cm.key.name`.

To avoid translating useless keys, I suggest checking these issues.

I would assign it to myself (but I don't know when I'll work on this), so I will leave it unassigned FTM.

**Comment by 12rambau** [comment]
```python
from pathlib import Path

folder = Path().home()/"modules"/"se.plan"
cm.key_use(folder, "cm")
```

There are 108 items I'm going to check their use carefully
