### ISSUE TITLE
Description length exceeds maximum error

### ISSUE THREAD

**Issue by thinn23** [sepal-contrib/se.plan#195]
I tried to run the se.plan and got this error back. **Description length exceeds maximum**
the link to my Recipe: https://drive.google.com/file/d/19EWxvRHfI-jwHvz5Fl_rBr85t77FSvX_/view?usp=share_link
![error](https://user-images.githubusercontent.com/125016493/218198102-7decaa1d-0903-44d1-8701-d1d9548781bb.png)

**Comment by dfguerrerom** [comment]
this error has been fixed in the new se.plan version that will be released on production in the next few weeks

**Comment by thinn23** [comment]
Many thanks a lot, Daniel.

Best regards,
Thinn
