### ISSUE TITLE
Failed to load model class 'HTMLModel' from module '@jupyter-widgets/controls'

### ISSUE THREAD

**Issue by ulfboge** [sepal-contrib/se.plan#200]
Dear SEPAL,
When I run the se.plan-app I get a javascript error (see attached). Could you please help me with this? 

Thank you!

Kind regards,
Johan
[SEPAL - error message.txt](https://github.com/sepal-contrib/se.plan/files/11370985/SEPAL.-.error.message.txt)
![2023-05-02 10_03_14-S E P A L - Person 1 – Microsoft​ Edge](https://user-images.githubusercontent.com/53839582/235612341-86682d47-915a-4653-998f-d3faa8a0914e.png)

**Comment by 12rambau** [comment]
thanks Johan for your feedback, 

It's a compatibility issue between SEPAL and se.plan ipywidgets version. SEPAL will be updated after the last session of the e-learning academy and this issue should disapear at the same time. 

Normaly it should not change anything to the result of the computation Have you tried to computeer the resoration index ?

**Comment by ulfboge** [comment]
Thank you, Pierrick, for your quick reply!

Thank you for the information. When in time is the update expected (i.e., when is the e-learning academy over 😊)?

Yes, the restoration dashboard works, as do the export of the csv. I found the data format in the csv slightly non-intuitive, but the numbers made sense when I used the dashboard as a reference.

Kind regards,
Johan

**Comment by 12rambau** [comment]
The module 5 is today, I hope hat we will reroll SEPAL by the end of the week. I'll leave this issue open until it's solved on the production server

**Comment by yfinegold** [comment]
Dear Johan,
Are you able to compute the map and dashboard? The error on the map is still there but does not affect the functionality of the tool so you should be able to use the tool without a problem.

**Comment by ulfboge** [comment]
Dear Yelena,

Thank you for your reply. Yes, the map and dashboard can be computed.

Kind regards,
Johan

**Comment by ulfboge** [comment]
Dear Yelena,

I wonder about the unit in the Biophysical category "Annual rainfall". It says it is mm/yr, but the original dataset has this parameter as meter/year. In any scenario, the unit or the actual values do not make sense to me. Looking at a region such as Malanje, Angola, the annual rainfall is set between 0.03 - 0-06 mm/yr. That is almost nothing. Even if it was m/year it does sound very little to me.

Could you please advise on how I should interpret this?

Thank you!

Kind regards,
Johan

**Comment by dfguerrerom** [comment]
fixed with https://github.com/sepal-contrib/se.plan/commit/a23c741e29b84d065ef77af3887c18232d032551
