### ISSUE TITLE
error when opening se.plan - maybe from sepal_ui?

### ISSUE THREAD

**Issue by yfinegold** [sepal-contrib/se.plan#201]
Hey Pierrick - we have an issue reported by Ken upon opening se.plan
![image](https://github.com/sepal-contrib/se.plan/assets/5813936/64c5e300-6bd4-4864-83b8-229f708da2f2)

**Comment by yfinegold** [comment]
I am trying to tempt you with Git issues ahahah  
Here is the full error : 
 

--------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)

File /tmp/ipykernel_435/1129545190.py:4

      1 from component import tile

      3 # create the tile

----> 4 rp_aoi = tile.CustomAoiTile(methods=["-POINTS"])

      6 # this tile will only be displayed if voila is launch from this notebook

      7 rp_aoi

 

File ~/shared/apps/se.plan/component/tile/custom_aoi_tile.py:28, in CustomAoiTile.__init__(self, methods, gee, **kwargs)

     24 self.map.dc.hide()

     26 # create the view

     27 # the view include the model

---> 28 self.view = aoi.AoiView(methods=methods, map_=self.map, gee=gee, **kwargs)

     29 self.view.elevation = 0

     31 # organise them in a layout

 

File /usr/local/share/jupyter/kernels/venv-se.plan/venv/lib/python3.8/site-packages/sepal_ui/aoi/aoi_view.py:261, in AoiView.__init__(self, methods, map_, gee, folder, **kwargs)

    258 gee is False or su.init_ee()

    260 # get the model

--> 261 self.model = AoiModel(sw.Alert(), gee=gee, folder=folder, **kwargs)

    263 # get the map if filled

    264 self.map_ = map_

 

File /usr/local/share/jupyter/kernels/venv-se.plan/venv/lib/python3.8/site-packages/sepal_ui/aoi/aoi_model.py:167, in AoiModel.__init__(self, alert, gee, vector, admin, asset, folder)

    165 if gee:

    166     su.init_ee()

--> 167     self.folder = folder or ee.data.getAssetRoots()[0]["id"]

    169 # the Alert used to display information

    170 self.alert = alert

 

IndexError: list index out of range

---------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)

Cell In[4], line 2

      1 # add tiles

----> 2 get_ipython().run_line_magic('run', "'aoi_ui.ipynb'")

      3 get_ipython().run_line_magic('run', "'questionnaire_ui.ipynb'")

      4 get_ipython().run_line_magic('run', "'compute_ui.ipynb'")

 

File /usr/local/share/jupyter/kernels/venv-se.plan/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py:2364, in InteractiveShell.run_line_magic(self, magic_name, line, _stack_depth)

   2362     kwargs['local_ns'] = self.get_local_scope(stack_depth)

   2363 with self.builtin_trap:

-> 2364     result = fn(*args, **kwargs)

   2365 return result

 

File /usr/local/share/jupyter/kernels/venv-se.plan/venv/lib/python3.8/site-packages/IPython/core/magics/execution.py:717, in ExecutionMagics.run(self, parameter_s, runner, file_finder)

    715     with preserve_keys(self.shell.user_ns, '__file__'):

    716         self.shell.user_ns['__file__'] = filename

--> 717         self.shell.safe_execfile_ipy(filename, raise_exceptions=True)

    718     return

    720 # Control the response to exit() calls made by the script being run

 

File /usr/local/share/jupyter/kernels/venv-se.plan/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py:2870, in InteractiveShell.safe_execfile_ipy(self, fname, shell_futures, raise_exceptions)

   2868 result = self.run_cell(cell, silent=True, shell_futures=shell_futures)

   2869 if raise_exceptions:

-> 2870     result.raise_error()

   2871 elif not result.success:

  2872     break

 

File /usr/local/share/jupyter/kernels/venv-se.plan/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py:266, in ExecutionResult.raise_error(self)

    264     raise self.error_before_exec

    265 if self.error_in_exec is not None:

--> 266     raise self.error_in_exec

 

    [... skipping hidden 1 frame]

 

File /tmp/ipykernel_435/1129545190.py:4

      1 from component import tile

      3 # create the tile

----> 4 rp_aoi = tile.CustomAoiTile(methods=["-POINTS"])

      6 # this tile will only be displayed if voila is launch from this notebook

      7 rp_aoi

 

File ~/shared/apps/se.plan/component/tile/custom_aoi_tile.py:28, in CustomAoiTile.__init__(self, methods, gee, **kwargs)

     24 self.map.dc.hide()

     26 # create the view

     27 # the view include the model

---> 28 self.view = aoi.AoiView(methods=methods, map_=self.map, gee=gee, **kwargs)

     29 self.view.elevation = 0

     31 # organise them in a layout

 

File /usr/local/share/jupyter/kernels/venv-se.plan/venv/lib/python3.8/site-packages/sepal_ui/aoi/aoi_view.py:261, in AoiView.__init__(self, methods, map_, gee, folder, **kwargs)

    258 gee is False or su.init_ee()

    260 # get the model

--> 261 self.model = AoiModel(sw.Alert(), gee=gee, folder=folder, **kwargs)

    263 # get the map if filled

    264 self.map_ = map_

 

File /usr/local/share/jupyter/kernels/venv-se.plan/venv/lib/python3.8/site-packages/sepal_ui/aoi/aoi_model.py:167, in AoiModel.__init__(self, alert, gee, vector, admin, asset, folder)

    165 if gee:

    166     su.init_ee()

--> 167     self.folder = folder or ee.data.getAssetRoots()[0]["id"]

    169 # the Alert used to display information

    170 self.alert = alert

 

IndexError: l

**Comment by dfguerrerom** [comment]
Hi Yelena, at first sight, to me, it looks like the user has not created the "home" folder in GEE, he can check how to create it here: https://docs.sepal.io/en/latest/setup/gee.html#initialize-the-home-folder.

**Comment by dfguerrerom** [comment]
the user could fix this issue just by disconnecting and connecting his GEE account.
