### ISSUE TITLE
"list index out of range" error when creating new recipe

### ISSUE THREAD

**Issue by weeix** [sepal-contrib/se.plan#215]
Actual Result:

![image](https://github.com/sepal-contrib/se.plan/assets/6592791/a9994d98-f159-4609-8db8-f523c7680dc6)

Expected Result:

The process can proceed normally, or display an error message that makes sense.

**Comment by dfguerrerom** [comment]
Thanks for reporting this error.
This happens because there's not a `home folder` initialized in GEE, can you confirm you have one?
We will fix the issue so users will have a more meaningful error.

**Comment by weeix** [comment]
You’re totally right. After I switched on the legacy asset and made a home folder, I can whip up a recipe now. Thanks.

![image](https://github.com/sepal-contrib/se.plan/assets/6592791/1d752423-ef08-444e-a2c1-b75991bb4a13)
