### ISSUE TITLE
Unable to load recipes that utilize a GEE resource as the AOI

### ISSUE THREAD

**Issue by weeix** [sepal-contrib/se.plan#216]
The app is unable to load recipes that utilize a Google Earth Engine resource as the Area of Interest. I got this error message:

> Error in field 'aoi.primary.asset_json': {'pathname': 'users/royalforestdept/mamang', 'column': 'ALL', 'value': None} is not of type 'string', 'null'

![image](https://github.com/sepal-contrib/se.plan/assets/6592791/a812cad0-5f7d-48b8-a0b2-a8a4ab58a542)

**Comment by dfguerrerom** [comment]
fixed with https://github.com/sepal-contrib/se.plan/commit/960254a2c816949ecfff92da0a5173f619f5fb28
