### ISSUE TITLE
Se.plan recipe can note create the new recipe

### ISSUE THREAD

**Issue by haipn1983** [sepal-contrib/se.plan#225]
We can note create new se.plan recipe as image below
<img width="1604" alt="seplan_recipe" src="https://github.com/sepal-contrib/se.plan/assets/26912521/0460c3d3-099d-4946-a006-064cb3a9eeda">

**Comment by dfguerrerom** [comment]
that problem was solved with https://github.com/sepal-contrib/se.plan/commit/59069925d5c5274999ff937d16bfaadb0e6c1ec5
