### ISSUE TITLE
plantation_growth_rates masks out 0 values

### ISSUE THREAD

**Issue by dfguerrerom** [sepal-contrib/se.plan#243]
Problem
-----------

The restoration suitability index for Afghanistan is masked in 95% of the country. This happens because the `plantation_growth_rates` benefit layer has areas where the rate is 0, in which case, at the percentile calculation, the value will be masked out, and consequently not included for the benefit calculation.

Layer overview
-------------------
https://code.earthengine.google.com/ba55e64aa620933d013637ea69fa5ba2

with @yfinegold, we think we can just `.add(1)` to the original layer and avoid this exclusion.

**Comment by luislizcano** [comment]
@dfguerrerom you can find the edited layer here: ```"projects/se-plan/assets/inputLayers/yields-4326-edited"```. However, note that the original distribution indicates min valid values of 0.04. So be aware that zeros are ones in the edited layer, and those ones will be considered valid for any calculations.

**Comment by dfguerrerom** [comment]
> projects/se-plan/assets/inputLayers/yields-4326-edited

Would you mind making this layer public? thanks!

**Comment by luislizcano** [comment]
Done!

**Comment by dfguerrerom** [comment]
This was done with https://github.com/sepal-contrib/se.plan/commit/28097d83d21acc6673f97682b6a3318bab0053f5, I'm waiting for a sepal release to release this change.
