### ISSUE TITLE
custom benefits

### ISSUE THREAD

**Issue by 12rambau** [sepal-contrib/se.plan#83]
create a big green + btn to add fully customized benefits

**Comment by jdilger** [comment]
will this allow customization of the landcover layer as well?

**Comment by 12rambau** [comment]
landcover customization is already possible, you just have to use a landcover that respects the CCI classes right ?

**Comment by jdilger** [comment]
Correct, but is there somewhere to actually change that out in the UI? I don't see how anyone could do it now without editing the layer list.

**Comment by dfguerrerom** [comment]
this issue is deprecated, now it can be done with se.plan v1.0
